# Generated by Django 4.2.19 on 2025-02-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigQueryContact',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email_history', models.TextField()),
                ('company_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('industry_name', models.CharField(max_length=255)),
                ('company_country_name', models.CharField(max_length=255)),
                ('company_size', models.CharField(max_length=255)),
                ('employees_range', models.CharField(max_length=255)),
                ('mobile_phone', models.CharField(max_length=255)),
                ('personal_phone', models.CharField(max_length=255)),
                ('company_phone', models.CharField(max_length=255)),
                ('people_in_company', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'managed': False,
            },
        ),
    ]
